version: '3.9'

services:
  db:
    image: mysql:8.0.31
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=dbexample
      - MYSQL_USER=userexample
      - MYSQL_PASSWORD=passwordexample
    expose:
      - 3306

  wp:
    image: wordpress:6.0.2
    volumes:
      - wp_data:/var/www/html
    ports:
      - 80:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_NAME=dbexample
      - WORDPRESS_DB_USER=userexample
      - WORDPRESS_DB_PASSWORD=passwordexample

  admin:
    image: phpmyadmin:5.2.0
    restart: always
    ports:
      - 82:80

volumes:
  db_data:
  wp_data:
