version: '3.9'

services:
  db:
    image: mysql:8.0.31
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      # - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
      - MYSQL_DATABASE=dbexample
      - MYSQL_USER=userexample
      # - MYSQL_PASSWORD=passwordexample
      - MYSQL_PASSWORD_FILE=/run/secrets/db_password
    expose:
      - 3306
    secrets:
      - db_root_password
      - db_password

  wp:
    image: wordpress:6.0.2
    volumes:
      - wp_data:/var/www/html
    ports:
      - 80:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_NAME=dbexample
      - WORDPRESS_DB_USER=userexample
      # - WORDPRESS_DB_PASSWORD=passwordexample
      - WORDPRESS_DB_PASSWORD_FILE=/run/secrets/db_password
    secrets:
      - db_root_password
      - db_password

  admin:
    image: phpmyadmin:5.2.0
    restart: always
    ports:
      - 82:80

secrets:
  db_root_password:
    file: db_root_password.txt
  db_password:
    file: db_password.txt

volumes:
  db_data:
  wp_data:
